apiVersion: v1
kind: Service
metadata:
  name: wordpress-srv
  labels:
    name: wordpress-srv
spec:
  type: LoadBalancer
  ports:
    # the port that this service serve on
    - port: 80
  selector:
    name: wordpress
  
